### ISSUE TITLE
MVG url change

### ISSUE THREAD

**Issue by tai42** [Lynbarry/mvg-api#13]
It seems that MVG changed the urls to access the API:
Old: https://www.mvg.de/fahrinfo/api/departure/
New: https://www.mvg.de/api/fahrinfo/departure/
And 
Old: https://www.mvg.de/fahrinfo/api/location/
New: https://www.mvg.de/api/fahrinfo/location/

After changeing the urls the code worked again

**Comment by Lynbarry** [comment]
Thanks, changed it just now and released version 3.1.0 which should work.
