### ISSUE TITLE
yarn build: failed to minify

### ISSUE THREAD

**Issue by florian-senn** [Lynbarry/mvg-api#5]
I've included your package to a React App and got this error when running yarn build:

yarn build v0.27.5
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/@fsenn/mvg-api/lib/mvgApi.js:18 

Read more here: http://bit.ly/2tRViJ9

**Comment by Lynbarry** [comment]
Hey, thanks for bringing this up!
I'll look into it now!

**Comment by Lynbarry** [comment]
I think I fixed it by transpiling to ES5 and then publishing the transpiled version. At least it worked with a dummy react App I just created to try it out.

You can use the version 1.1.0 which I just published and see if it works for you, too.

**Comment by florian-senn** [comment]
Hi Lynbarry,

thanks for your great work!
